//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_View.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_View.Properties.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All the saveworks.
        /// </summary>
        public static string all_saveworks {
            get {
                return ResourceManager.GetString("all_saveworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string btnChooseValidate {
            get {
                return ResourceManager.GetString("btnChooseValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string btnChooseValidateDelete {
            get {
                return ResourceManager.GetString("btnChooseValidateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string btnCryptoValidate {
            get {
                return ResourceManager.GetString("btnCryptoValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btnExtensionDelete {
            get {
                return ResourceManager.GetString("btnExtensionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string btnPriorityExtensionDelete {
            get {
                return ResourceManager.GetString("btnPriorityExtensionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string btnPriorityValidate {
            get {
                return ResourceManager.GetString("btnPriorityValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string btnValidate {
            get {
                return ResourceManager.GetString("btnValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Savework&apos;s creation.
        /// </summary>
        public static string create_lbl {
            get {
                return ResourceManager.GetString("create_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your extension.
        /// </summary>
        public static string crypto_lbl {
            get {
                return ResourceManager.GetString("crypto_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination folder :.
        /// </summary>
        public static string dest_lbl {
            get {
                return ResourceManager.GetString("dest_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About us.
        /// </summary>
        public static string header_about {
            get {
                return ResourceManager.GetString("header_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        public static string header_config {
            get {
                return ResourceManager.GetString("header_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a savework.
        /// </summary>
        public static string header_create {
            get {
                return ResourceManager.GetString("header_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a savework.
        /// </summary>
        public static string header_delete {
            get {
                return ResourceManager.GetString("header_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit a savework.
        /// </summary>
        public static string header_edit {
            get {
                return ResourceManager.GetString("header_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string header_english {
            get {
                return ResourceManager.GetString("header_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string header_french {
            get {
                return ResourceManager.GetString("header_french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your business software.
        /// </summary>
        public static string header_job {
            get {
                return ResourceManager.GetString("header_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string header_language {
            get {
                return ResourceManager.GetString("header_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log file.
        /// </summary>
        public static string header_logfile {
            get {
                return ResourceManager.GetString("header_logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        public static string header_logs {
            get {
                return ResourceManager.GetString("header_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string header_quit {
            get {
                return ResourceManager.GetString("header_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string header_run {
            get {
                return ResourceManager.GetString("header_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State file.
        /// </summary>
        public static string header_statefile {
            get {
                return ResourceManager.GetString("header_statefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This project has been realized in the system programming project in third year&apos;s IT specialty class at CESI Bordeaux. Made By group 6 (Clément Courtembert Gaillard, Elouan Jeannot, Maxime Ferreira, Mathéo Berger)..
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the savework you want to delete.
        /// </summary>
        public static string lblchoosedelete {
            get {
                return ResourceManager.GetString("lblchoosedelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coming soon....
        /// </summary>
        public static string lblComing {
            get {
                return ResourceManager.GetString("lblComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your extension is not in the list? You can fill it.
        /// </summary>
        public static string lblExtension {
            get {
                return ResourceManager.GetString("lblExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert a specific extension.
        /// </summary>
        public static string lblPriorityExtension {
            get {
                return ResourceManager.GetString("lblPriorityExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your savework has been created.
        /// </summary>
        public static string msgCreated {
            get {
                return ResourceManager.GetString("msgCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your savework has been deleted.
        /// </summary>
        public static string msgDeleted {
            get {
                return ResourceManager.GetString("msgDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your savework has been executed.
        /// </summary>
        public static string msgExecuted {
            get {
                return ResourceManager.GetString("msgExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your extension has been deleted.
        /// </summary>
        public static string msgExtension {
            get {
                return ResourceManager.GetString("msgExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The path of your business software is the following one?.
        /// </summary>
        public static string msgPath {
            get {
                return ResourceManager.GetString("msgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Savework&apos;s name :.
        /// </summary>
        public static string name_lbl {
            get {
                return ResourceManager.GetString("name_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority file extensions.
        /// </summary>
        public static string priority_header {
            get {
                return ResourceManager.GetString("priority_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your priority file extension.
        /// </summary>
        public static string priority_lbl {
            get {
                return ResourceManager.GetString("priority_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a savework to run.
        /// </summary>
        public static string Savework_to_run {
            get {
                return ResourceManager.GetString("Savework_to_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum file size for parallel transfer.
        /// </summary>
        public static string sizeFile_header {
            get {
                return ResourceManager.GetString("sizeFile_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source folder :.
        /// </summary>
        public static string source_lbl {
            get {
                return ResourceManager.GetString("source_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave soft.
        /// </summary>
        public static string txtBlckSoftName {
            get {
                return ResourceManager.GetString("txtBlckSoftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the destination folder.
        /// </summary>
        public static string txtDest {
            get {
                return ResourceManager.GetString("txtDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your extension....
        /// </summary>
        public static string txtExtension {
            get {
                return ResourceManager.GetString("txtExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the source folder.
        /// </summary>
        public static string txtSource {
            get {
                return ResourceManager.GetString("txtSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type:.
        /// </summary>
        public static string type_lbl {
            get {
                return ResourceManager.GetString("type_lbl", resourceCulture);
            }
        }
    }
}
