//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_View.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_View.Properties.ResourceFR", typeof(ResourceFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les travaux de sauvegarde.
        /// </summary>
        public static string all_saveworks {
            get {
                return ResourceManager.GetString("all_saveworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btnChooseValidate {
            get {
                return ResourceManager.GetString("btnChooseValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btnChooseValidateDelete {
            get {
                return ResourceManager.GetString("btnChooseValidateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btnCryptoValidate {
            get {
                return ResourceManager.GetString("btnCryptoValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btnExtensionDelete {
            get {
                return ResourceManager.GetString("btnExtensionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btnPriorityExtensionDelete {
            get {
                return ResourceManager.GetString("btnPriorityExtensionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btnPriorityValidate {
            get {
                return ResourceManager.GetString("btnPriorityValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btnValidate {
            get {
                return ResourceManager.GetString("btnValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un travail de sauvegarde.
        /// </summary>
        public static string create_lbl {
            get {
                return ResourceManager.GetString("create_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une ou plusieurs extensions.
        /// </summary>
        public static string crypto_lbl {
            get {
                return ResourceManager.GetString("crypto_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire de destination.
        /// </summary>
        public static string dest_lbl {
            get {
                return ResourceManager.GetString("dest_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos.
        /// </summary>
        public static string header_about {
            get {
                return ResourceManager.GetString("header_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        public static string header_config {
            get {
                return ResourceManager.GetString("header_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un travail de sauvegarde.
        /// </summary>
        public static string header_create {
            get {
                return ResourceManager.GetString("header_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un travail de sauvegarde.
        /// </summary>
        public static string header_delete {
            get {
                return ResourceManager.GetString("header_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un travail de sauvegarde.
        /// </summary>
        public static string header_edit {
            get {
                return ResourceManager.GetString("header_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais.
        /// </summary>
        public static string header_english {
            get {
                return ResourceManager.GetString("header_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string header_french {
            get {
                return ResourceManager.GetString("header_french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir votre application métier.
        /// </summary>
        public static string header_job {
            get {
                return ResourceManager.GetString("header_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage.
        /// </summary>
        public static string header_language {
            get {
                return ResourceManager.GetString("header_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier de logs.
        /// </summary>
        public static string header_logfile {
            get {
                return ResourceManager.GetString("header_logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        public static string header_logs {
            get {
                return ResourceManager.GetString("header_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string header_quit {
            get {
                return ResourceManager.GetString("header_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter.
        /// </summary>
        public static string header_run {
            get {
                return ResourceManager.GetString("header_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier d&apos;état.
        /// </summary>
        public static string header_statefile {
            get {
                return ResourceManager.GetString("header_statefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce projet a été réalisé dans le cadre du bloc programmation système en 3ème année spécialité informatique à CESI Bordeaux par le groupe 6 (Clément Courtembert Gaillard, Elouan Jeannot, Maxime Ferreira, Mathéo Berger)..
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quel travail de sauvegarde souhaitez-vous supprimer ?.
        /// </summary>
        public static string lblchoosedelete {
            get {
                return ResourceManager.GetString("lblchoosedelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A venir....
        /// </summary>
        public static string lblComing {
            get {
                return ResourceManager.GetString("lblComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insérer une extension spécifique.
        /// </summary>
        public static string lblExtension {
            get {
                return ResourceManager.GetString("lblExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insérer une extension spécifique.
        /// </summary>
        public static string lblPriorityExtension {
            get {
                return ResourceManager.GetString("lblPriorityExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre sauvegarde a bien été créée.
        /// </summary>
        public static string msgCreated {
            get {
                return ResourceManager.GetString("msgCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre sauvegarde a bien été suprimée.
        /// </summary>
        public static string msgDeleted {
            get {
                return ResourceManager.GetString("msgDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre sauvegarde a bien été exécutée.
        /// </summary>
        public static string msgExecuted {
            get {
                return ResourceManager.GetString("msgExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre extension a été supprimée.
        /// </summary>
        public static string msgExtension {
            get {
                return ResourceManager.GetString("msgExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin d&apos;accès de votre application métier est-il bien celui-ci ?.
        /// </summary>
        public static string msgPath {
            get {
                return ResourceManager.GetString("msgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail de sauvegarde :.
        /// </summary>
        public static string name_lbl {
            get {
                return ResourceManager.GetString("name_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions de fichiers prioritaires.
        /// </summary>
        public static string priority_header {
            get {
                return ResourceManager.GetString("priority_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez la ou les extensions de fichier prioritaire.
        /// </summary>
        public static string priority_lbl {
            get {
                return ResourceManager.GetString("priority_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez un travail de sauvegarde à exécuter.
        /// </summary>
        public static string Savework_to_run {
            get {
                return ResourceManager.GetString("Savework_to_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille de fichier de transfert simultané maximale.
        /// </summary>
        public static string sizeFile_header {
            get {
                return ResourceManager.GetString("sizeFile_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire source :.
        /// </summary>
        public static string source_lbl {
            get {
                return ResourceManager.GetString("source_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel de Sauvegarde Facile.
        /// </summary>
        public static string txtBlckSoftName {
            get {
                return ResourceManager.GetString("txtBlckSoftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le répertoire de destination.
        /// </summary>
        public static string txtDest {
            get {
                return ResourceManager.GetString("txtDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre extension....
        /// </summary>
        public static string txtExtension {
            get {
                return ResourceManager.GetString("txtExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le répertoire source.
        /// </summary>
        public static string txtSource {
            get {
                return ResourceManager.GetString("txtSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type :.
        /// </summary>
        public static string type_lbl {
            get {
                return ResourceManager.GetString("type_lbl", resourceCulture);
            }
        }
    }
}
